### ISSUE TITLE
Precompiled Windows binaries

### ISSUE THREAD

**Issue by NightFright2k19** [svkaiser/strife-ve#12]
Looking for latest compiled Windows (x86 or x64) builds without GOG or Steam dependencies, if possible.

**Comment by lehjr** [comment]
You realize this is a 30 year old DOS game, right?

**Comment by NightFright2k19** [comment]
Same can be said about Doom, ROTT, Duke3D, Blood, Shadow Warrior... And they are all still quite alive. Thanks to ports. 

Admittedly, Strife is probably the least known/popular of the Doom family, but it doesn't mean it's dead.

**Comment by lehjr** [comment]
But you’re not likely to get a “windows” port of a dos game that came out
in the 90’s let alone 64 bit version.

**Comment by NightFright2k19** [comment]
Interesting. What is this, then? Maybe it's not 64-bit, but it works. And there's Chocolate/Crispy Strife, GZDoom... We have already quite a few options. ;)

But this doesn't get us anywhere, so from my side that's it.

**Comment by lehjr** [comment]
Reverse engineering code from a 30 year old game doesn’t magically make it a modern title. Sent from my iPhoneOn Feb 10, 2024, at 6:23 PM, NightFright2k19 ***@***.***> wrote:﻿
Interesting. What is this, then? Maybe it's not 64-bit, but it works. And there's Chocolate/Crispy Strife, GZDoom... We have already quite a few options. ;)
But this doesn't get us anywhere, so from my side that's it.

**Comment by aliceif** [comment]
This is in fact a modern cross platform 64-bit application - it literally has x86_64 support (at least on Linux) mentioned in a Readme file. No DOS emulation required.

Many old games based on id software engines have "source ports" available - reimplementations for current operating systems based on id's officially published source code - no complex reverse engineering needed here.

Sadly I don't know where one can find the builds OP originally asked for, but when strive-ve originally came out I did help someone compile it in visual studio and I don't remember it being too complicated, so you can probably do it yourself.

**Comment by lehjr** [comment]
Well, you already have your answer then. Good luck.
